[tools]
zig = "0.13.0"

[tasks.build]
description = "Build the project"
run = "zig build"

[tasks.run]
description = "Run the CLI"
run = "zig build run"

[tasks.test]
description = "Run all tests"
run = "zig build test"

[tasks.clean]
description = "Clean build artifacts"
run = "rm -rf zig-cache zig-out"

[tasks.dev]
description = "Development setup - build and test"
run = ["zig build", "zig build test"]

[tasks.fmt]
description = "Format Zig code"
run = "zig fmt src/"