[tools]
dart = "3.8.2"

[env]
# Ensure Dart binaries are in PATH
PATH = "{{config_root}}/.mise/installs/dart/3.8.2/bin:$PATH"

[tasks.deps]
description = "Install Dart dependencies"
run = "dart pub get"

[tasks.test]
description = "Run all tests"
run = "dart test"

[tasks.test-coverage]
description = "Run tests with coverage"
run = [
  "dart pub global activate coverage 1.2.0",
  "dart test --coverage=coverage",
  "dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info"
]

[tasks.analyze]
description = "Analyze Dart code"
run = "dart analyze"

[tasks.format]
description = "Format Dart code"
run = "dart format ."

[tasks.fix]
description = "Apply automated fixes"
run = "dart fix --apply"

[tasks.build]
description = "Build version information"
run = "dart run build_runner build"

[tasks.verify]
description = "Verify build"
run = "dart run build_verify"

[tasks.run]
description = "Run the CLI"
run = "dart run bin/popshop.dart"

[tasks.dev]
description = "Development setup - install dependencies and build"
run = [
  "dart pub get",
  "dart run build_runner build"
]