name: popshop
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  http: ^1.4.0
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0

executables:
  popshop:
